# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Erika Senft Miller
description: A conceptual performance artist actively exploring and embracing the power of movement through rigorous academic research, a careful pattern of creative productivity, and in-depth multimedia integration and documentation of her work.
baseurl: "/erika-senft-miller/"
url: "" 
collections:
  projects:
    output: true
    permalink: /:collection/:name
  forms:
    output: true
    permalink: /upload/:name
  pages:
    output: true
    permalink: /:title/  

kramdown:  
  parse_block_html: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
